language: node_js

node_js:
  - "10"

services:
  - docker

install:
  - echo 'skip install'

script:
  - echo 'skip script'

after_success:
  - docker --version
  - make docker adapter=kaiko
  - docker tag kaiko-adapter:latest kybernetwork/external-adapters-js:kaiko-"$TRAVIS_COMMIT"
  - docker tag kaiko-adapter:latest kybernetwork/external-adapters-js:kaiko-latest
  - make docker adapter=coingecko
  - docker tag coingecko-adapter:latest kybernetwork/external-adapters-js:coingecko-"$TRAVIS_COMMIT"
  - docker tag coingecko-adapter:latest kybernetwork/external-adapters-js:coingecko-latest
  - make docker adapter=fixer
  - docker tag fixer-adapter:latest kybernetwork/external-adapters-js:fixer-"$TRAVIS_COMMIT"
  - docker tag fixer-adapter:latest kybernetwork/external-adapters-js:fixer-latest

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
